# SPDX-FileCopyrightText: 2021 Johannes Siipola
# SPDX-License-Identifier: CC0-1.0

version: "3.9"
services:
  default:
    build:
      context: .
      dockerfile: imagemagick.Dockerfile
    tty: true
    volumes:
      - .:/home/project
