name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup docker
        run: docker-compose up -d
      - name: Install composer
        run: docker exec -w /home/project jpeg-xl-encode_default_1 bash -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
      - name: Validate composer.json and composer.lock
        run: docker exec -w /home/project jpeg-xl-encode_default_1 bash -c "composer validate"
      - name: Install dependencies
        run: docker exec -w /home/project jpeg-xl-encode_default_1 bash -c "composer install --prefer-dist --no-progress --no-suggest"
      - name: Run test suite
        run: docker exec -w /home/project jpeg-xl-encode_default_1 bash -c "./vendor/bin/codecept run --debug -vvv"
