# SPDX-FileCopyrightText: 2021 Johannes Siipola
# SPDX-License-Identifier: CC0-1.0

name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: docker-compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Setup docker
        run: docker-compose up --build -d
      - name: Validate composer.json and composer.lock
        run: docker exec -w /home/project jpeg-xl-encode_default_1 bash -c "composer validate"
      - name: Install dependencies
        run: docker exec -w /home/project jpeg-xl-encode_default_1 bash -c "composer install --prefer-dist --no-progress --no-suggest"
      - name: Run test suite
        run: docker exec -w /home/project jpeg-xl-encode_default_1 bash -c "export XDEBUG_MODE=coverage; ./vendor/bin/codecept run --debug -vvv --coverage --coverage-xml"
      - uses: codecov/codecov-action@v2
        with:
          files: ./tests/_output/coverage.xml
          verbose: true